CREATE TABLE products(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	rating FLOAT DEFAULT 0,
	stock INT NOT NULL
	);