CREATE TABLE products(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	rating FLOAT DEFAULT 0 NOT NULL,
	stock INT NOT NULL
);
	
CREATE TABLE image_products(
	id INT AUTO_INCREMENT PRIMARY KEY,
	url TEXT NOT NULL,
	product_id INT NOT NULL,
	FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);