CREATE TABLE products(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	rating FLOAT DEFAULT 0,
	stock INT NOT NULL
	);
	
CREATE TABLE image_products(
	id INT AUTO_INCREMENT PRIMARY KEY,
	url TEXT,
	product_id INT,
	FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
	);