CREATE TABLE carts(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE cart_items(
	id INT AUTO_INCREMENT PRIMARY KEY,
	quantity INT NOT NULL,
	subtotal DECIMAL(10,2) NOT NULL,
	cart_id INT NOT NULL,
	product_id INT NOT NULL,
	FOREIGN KEY(cart_id) REFERENCES carts(id)ON DELETE CASCADE,
	FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
);
